config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root :to => redirect('/tasks')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_task.rb
class CategoriesTask < ApplicationRecord
  belongs_to :category
  belongs_to :task
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  has_and_belongs_to_many :categories
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @categories = Category.all
  end

  # GET /tasks/1/edit
  def edit
    @categories = Category.all
  end

  # POST /tasks
  # POST /tasks.json
  def create
    other_params, category_ids = task_params
    @task = Task.new(other_params)
    set_categories(category_ids, @task)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      other_params, category_ids = task_params

      # Set categories before updating the other params
      set_categories(category_ids, @task)

      if @task.update(other_params)
        if params[:no_show]
          head :no_content
          return
        end
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      all_params = params.require(:task).permit(:title, :due_date, :completed, categories: [])
      return all_params.except(:categories), all_params[:categories]
    end

    def set_categories(category_ids, task)
      if not category_ids
        return
      end

      @task.categories = [] # Clear as we don't want stray categories that have been deselected

      category_ids.each do |category_id|
        if category_id.empty?
          next
        end
        category = Category.find(category_id)
        if category.valid? and not @task.categories.include?(category)
          @task.categories.push(category)
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<div class="row">
  <div class="col s12">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Tasks</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td>
              <ul>
                <% category.tasks.each do |task| %>
                  <li><%= task.title %></li>
                <% end %>
              </ul>
            </td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="fixed-action-btn">
      <%= link_to new_category_path, class: "btn-floating btn-large red" do %>
        <i class="large material-icons">add</i>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Tasks:</strong>
  <ul>
    <% @category.tasks.each do |task| %>
      <li><%= task.title %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_header.html.erb
<nav class="nav-extended">
  <div class="col s12">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Dueet</a>
    </div>
    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <li class="tab"><a href=<%= tasks_path %>>Tasks</a></li>
        <li class="tab"><a href=<%= categories_path %>>Categories</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dueet</title>
    <%= csrf_meta_tags %>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.3/js/materialize.min.js"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12" style="height: 3rem;">
    <label>
      <%= form.check_box :completed, id: :task_completed %>
      <span>Completed</span>
    </label>
  </div>

  <div class="input-field col s12">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title %>
  </div>

  <div class="input-field col s12">
    <%= form.label :due_date %>
    <%= form.text_field :due_date, :class => 'datepicker' %>
  </div>

  <div class="input-field col s12">
    <%= select_tag "task[categories]", options_from_collection_for_select(categories, "id", "name", task.categories.map { |c| c.id }), multiple: true, id: "task_categories" %>
    <%= form.label :categories %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<div class="row">
  <%= render 'form', task: @task, categories: @categories %>
</div>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<div class="row">
  <div class="col s12">
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Due</th>
          <th>Categories</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td>
              <label>
                <input type="checkbox" taskid=<%= task.id %> <%= "checked" if task.completed %> id=<%= "#{task.id.to_s}_completion" %> />
                <span></span>
              </label>
            </td>
            <td><%= task.title %></td>
            <td><%= l task.due_date.to_date, format: :short if task.due_date %></td>
            <td>
              <ul>
                <% task.categories.each do |category| %>
                  <li><%= category.name %></li>
                <% end %>
              </ul>
            </td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="fixed-action-btn">
      <%= link_to new_task_path, class: "btn-floating btn-large red" do %>
        <i class="large material-icons">add</i>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<div class="row">
  <%= render 'form', task: @task, categories: @categories %>
</div>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Due:</strong>
  <td><%= l @task.due_date.to_date, format: :short if @task.due_date %></td>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Categories:</strong>
  <ul>
    <% @task.categories.each do |category| %>
      <li><%= category.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>